name: Workflow Demo

on: 
  workflow_dispatch: 

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: 
      group: production
      cancel-in-progress: true
    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID